projeto_clinica-main/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import IndexView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('clientes/', include('clientes.urls', namespace="clientes")),
    path('medicos/', include('medicos.urls', namespace="medicos")),
    path('sabermas/', views.SaberMasView.as_view(), name='sabermas'),
    path('terminos-privacidad/', views.TerminosPrivacidadView.as_view(), name='terminos_privacidad'),

]

projeto_clinica-main/medicos/urls.py
from django.urls import path
from . import views

app_name = 'medicos'

urlpatterns = [
    path('registro/medico/', views.medico_registro, name='medico_registro'),
    path('registro/especialidad/', views.especialidad_registro, name='especialidad_registro'),
    path('agendar/', views.agenda_registro, name='agendar_consulta'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    path('mis/consultas/', views.agenda_lista, name="agenda_lista"),
    path('admim/lista/medicos/', views.medico_lista, name="medicos_lista"),
    path('admim/lista/especialidades/', views.especialidad_lista, name="especialidad_lista")
    
]

projeto_clinica-main/medicos/models.py
from datetime import date
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.db.models.fields.related import ForeignKey

class Especialidad(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=200)
    
    def __str__(self):
        return f'{self.nombre}'
    
class Medico(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=200)
    email = models.EmailField(verbose_name="Email")
    rut = models.CharField(verbose_name="RUT", max_length=200)
    phone_regex = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message="Su número debe estar en el siguiente formato: \
                    '+56 9 9999-9999'.")

    telefono = models.CharField(verbose_name="Telefono",
                                validators=[phone_regex],
                                max_length=17, null=True, blank=True)
    especialidad = ForeignKey(Especialidad,
                               on_delete=models.CASCADE,
                               related_name='medicos')
    
    def __str__(self):
        return f'{self.nombre}'

def validar_dia(value):
    today = date.today()
    weekday = date.fromisoformat(f'{value}').weekday()

    if value < today:
        raise ValidationError('No es posible elegir una fecha caducada.')
    if (weekday == 5) or (weekday == 6):
        raise ValidationError('Elija un día hábil de la semana.')

class Agenda(models.Model):
    medico = ForeignKey(Medico, on_delete=models.CASCADE, related_name='agenda')
    dia = models.DateField(help_text="Introduzca una fecha", validators=[validar_dia])
    
    HORARIOS = (
        ("1", "07:00 a las 08:00"),
        ("2", "08:00 a las 09:00"),
        ("3", "09:00 a las 10:00"),
        ("4", "10:00 a las 11:00"),
        ("5", "11:00 a las 12:00"),
    )
    horario = models.CharField(max_length=10, choices=HORARIOS)
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name='Usuario', 
        on_delete=models.CASCADE
    )
    class Meta:
        unique_together = ('horario', 'dia')
        
    def __str__(self):
        return f'{self.dia.strftime("%b %d %Y")} - {self.get_horario_display()} - {self.medico}'

projeto_clinica-main/medicos/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Medico, Agenda, Especialidad


class TestMixinIsAdmin(UserPassesTestMixin):
    def test_func(self):
        is_admin_or_is_staff = self.request.user.is_superuser or \
            self.request.user.is_staff
        return bool(is_admin_or_is_staff)

    def handle_no_permission(self):
        messages.error(
            self.request, "¡No tienes permisos!"
        )
        return redirect("accounts:index")

class MedicoCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Medico
    login_url = 'accounts:login'
    template_name = 'medicos/registro.html'
    fields = ['nombre', 'crm', 'email', 'telefono', 'especialidad']
    success_url = reverse_lazy('medicos:medicos_lista')
    
class MedicoListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'medicos/medicos_list.html'

    def get_queryset(self):
        return Medico.objects.all().order_by('-pk')
    
class EspecialidadCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Especialidad
    login_url = 'accounts:login'
    template_name = 'medicos/registro.html'
    fields = ['nombre',]
    success_url = reverse_lazy('medicos:especialidad_lista')
    
class EspecialidadListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'medicos/especialidad_list.html'

    def get_queryset(self):
        return Especialidad.objects.all().order_by('-pk')


class AgendaCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'medicos/agenda_registro.html'
    fields = ['medico', 'dia', 'horario']
    success_url = reverse_lazy('medicos:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaUpdateView(LoginRequiredMixin, TestMixinIsAdmin, UpdateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'medicos/agenda_registro.html'
    fields = ['medico', 'dia', 'horario']
    success_url = reverse_lazy('medicos:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaDeleteView(LoginRequiredMixin, TestMixinIsAdmin, DeleteView):
    model = Agenda
    success_url = reverse_lazy('medicos:agenda_lista')
    template_name = 'form_delete.html'

    def get_success_url(self):
        messages.success(self.request, "¡Consulta eliminada exitosamente!")
        return reverse_lazy('medicos:agenda_lista')


class AgendaListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'medicos/agenda_list.html'

    def get_queryset(self):
        return Agenda.objects.filter().order_by('-pk')
    
medico_registro = MedicoCreateView.as_view()
medico_lista = MedicoListView.as_view()
especialidad_registro = EspecialidadCreateView.as_view()
especialidad_lista = EspecialidadListView.as_view()
agenda_registro = AgendaCreateView.as_view()
agenda_atualizar = AgendaUpdateView.as_view()
agenda_lista = AgendaListView.as_view()
agenda_deletar = AgendaDeleteView.as_view()

projeto_clinica-main/templates/medicos/agenda_list.html
{% extends "accounts/index.html" %}

{% block title %}
    Agendas
{% endblock %}

{% block accounts_container %}
<h2>Agendas Di</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Medico
            </th>
            <th>
                Dia
            </th>
            <th>
                Horario
            </th>
            <th>
                Opciones
            </th>
        </tr>
    </thead>
    <tbody>
        {% for consulta in object_list %}
        <tr>
            <td>
                <a href=""># {{ consulta.pk }}</a>
            </td>
            <td>
                {{ consulta.medico }}
            </td>
            <td>
                {{ consulta.dia|date:"d/m/Y" }}
            </td>
            <td>
                {{ consulta.get_horario_display }}
            </td>
            <td>
                <a href="{% url 'medicos:agendar_consulta_atualizar' consulta.id %}" class="text-primary" style="padding-left: 10px; text-decoration: none;">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'medicos:agendar_consulta_deletar' consulta.id %}" class="mr-1 text-danger" style="padding-left: 10px; text-decoration: none;">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

projeto_clinica-main/templates/medicos/agenda_registro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Cadastro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Agendar Consulta</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.medico.errors %} has-error{% endif %}">
                  <label for="{{ form.medico.auto_id }}" class="col-md-3 control-label">
                  {{ form.medico.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.medico class="form-control" %}

                    {% for error in form.medico.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.dia.errors %} has-error{% endif %}">
                  <label for="{{ form.dia.auto_ud }}" class="col-md-3 control-label">
                  {{ form.dia.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.dia type="date" class="form-control" placeholder="01/01/2022" %}
                    {% for error in form.dia.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.horario.errors %} has-error{% endif %}">
                  <label for="{{ form.horario.auto_id }}" class="col-md-3 control-label">
                  {{ form.horario.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.horario class="form-control" %}

                    {% for error in form.horario.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

projeto_clinica-main/templates/medicos/especialidad_list.html
{% extends "accounts/index.html" %}

{% block title %}
   Especialidade
{% endblock %}

{% block accounts_container %}
<h2>Especialidad</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
        </tr>
    </thead>
    <tbody>
        {% for especialidade in object_list %}
        <tr>
            <td>
                <a href=""># {{ especialidade.pk }}</a>
            </td>
            <td>
                {{ especialidade.nome }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

projeto_clinica-main/templates/medicos/medicos_list.html
{% extends "accounts/index.html" %}

{% block title %}
    Medicos
{% endblock %}

{% block accounts_container %}
<h2>Medicos</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
            <th>
                E-mail
            </th>
            <th>
                Rut 
            </th>
            <th>
                Especialidad
            </th>
            <th>
                Telefono
            </th>
        </tr>
    </thead>
    <tbody>
        {% for medico in object_list %}
        <tr>
            <td>
                <a href=""># {{ medico.pk }}</a>
            </td>
            <td>
                {{ medico.nome }}
            </td>
            <td>
                {{ medico.email }}
            </td>
            <td>
                {{ medico.rut }}
            </td>
            <td>
                {{ medico.especialidade }}
            </td>
            <td>
                {{ medico.telefone }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

projeto_clinica-main/templates/medicos/registro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Registro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">
                  {{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}