projeto_clinica-main/accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('datos/', views.update_user, name='update_user'),
    path('cambiar-contraseña/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('entrar/', views.login, name='login'),
    path('salir/', views.logout, name='logout'),
    path('recuperar-contraseña/',
        views.password_reset_request,
        name='password_reset'
    ),
    path('recuperar-contraseña-ok/', 
        auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path('recuperar-contraseña-completo/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password/password_reset_complete.html'
            ),
            name='password_reset_complete',
    ),
    path('recuperar-contraseña-confirmar/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password/password_reset_confirm.html',
        success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_confirm',
        views.password_reset_request,
        name="password_reset"
    )

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

projeto_clinica-main/clientes/urls.py
from django.urls import path
from . import views
from accounts import urls

app_name = 'clientes'

urlpatterns = [
    path('registro/', views.cliente_registro, name='cliente_registro'),
    path('atualizar/', views.cliente_atualizar, name='cliente_atualizar'),
    path('consultas/', views.consulta_lista, name='consulta_list'),
    path('consultas/crear/', views.consulta_registro, name='consulta_create'),
    path('consultas/editar/<int:pk>/', views.consulta_atualizar, name='consulta_update'),
    path('consultas/excluir/<int:pk>/', views.consulta_excluir, name='consulta_delete'),
    
    path('dashboard/',views.dashboard, name='dashboard'),
    path('meeting/',views.videocall, name='meeting'),
    path('logout/',views.logout_view, name='logout'),
    path('join/',views.join_room, name='join_room'),

]

projeto_clinica-main/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import IndexView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('clientes/', include('clientes.urls', namespace="clientes")),
    path('medicos/', include('medicos.urls', namespace="medicos")),
    path('sabermas/', views.SaberMasView.as_view(), name='sabermas'),
    path('terminos-privacidad/', views.TerminosPrivacidadView.as_view(), name='terminos_privacidad'),

]

projeto_clinica-main/medicos/urls.py
from django.urls import path
from . import views

app_name = 'medicos'

urlpatterns = [
    path('registro/medico/', views.medico_registro, name='medico_registro'),
    path('registro/especialidad/', views.especialidad_registro, name='especialidad_registro'),
    path('agendar/', views.agenda_registro, name='agendar_consulta'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    path('mis/consultas/', views.agenda_lista, name="agenda_lista"),
    path('admim/lista/medicos/', views.medico_lista, name="medicos_lista"),
    path('admim/lista/especialidades/', views.especialidad_lista, name="especialidad_lista")
    
]

projeto_clinica-main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %} Clinica {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}"media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index'%}" class="navbar-brand">Clinica</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'clientes:consulta_create'%}">Consultas</a>
            </li>
            {% if user.is_staff or user.is_superuser %}
            <li>
              <a href="{% url 'medicos:agendar_consulta'%}">Agendas</a>
            </li>
            <li>
              <a href="{% url 'medicos:medico_cadastro'%}">Medicos</a>
            </li>
            <li>
              <a href="{% url 'medicos:especialidade_cadastro'%}">Especialidades</a>
            </li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:index' %}">Mi Cuenta</a></li>
              <li><a href="{% url 'accounts:logout' %}">Salir</a></li>
            {% else %}
              <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
              <li><a href="{% url 'accounts:register' %}">Registro</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
    {% block messages %}
      {% for message in messages %}
        <div class='alert alert-{{ message.tags}}'>
        {{ message }}
        </div>
      {% endfor %}
    {% endblock messages %} 
		{% block container %} {% endblock %}
    <footer class="text-center">
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-unstyled">
            <a href="{% url 'index' %}">Inicio</a>  |  <a href="{% url 'terminos_privacidad' %}">Términos y Privacidad</a>
           </ul>
        </div>
      </div>
    </footer>
    
  </div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="https://kit.fontawesome.com/c2a3297ec9.js" crossorigin="anonymous"></script>
  <script src="{% static 'assets/bootstrap.min.js'%}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

projeto_clinica-main/templates/form_delete.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Apagar | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Apagar</h1>
        </div>
        <form action="" method="POST">
            <p>¿Desea eliminar?: <strong>{{ object }}</strong>?</p>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="#" onClick="history.go(-1)" class="btn btn-link"> Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

projeto_clinica-main/templates/index.html
{% extends 'base.html'%}
{% block container %}

    <div class="jumbotron page-header">
        <h1>Clinica Psicologica</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <p><a class="btn btn-primary" href="{% url 'sabermas' %}">Saber Más</a></p>
    </div>

{% endblock %}

projeto_clinica-main/templates/sabermas.html
{% extends 'base.html' %}

{% block container %}
<div class="clinica-psicologia">
    <h1>Clínica de Psicología</h1>
    <p>
        En nuestra clínica de psicología, ofrecemos una amplia gama de servicios para ayudar a mejorar la salud mental y el bienestar de nuestros pacientes.
    </p>
    <p>
        Nuestro equipo de psicólogos altamente calificados y experimentados está aquí para brindar apoyo y tratamiento para una variedad de desafíos emocionales y de salud mental.
    </p>
    <p>
        En la clínica, nos especializamos en:
    </p>
    <ul>
        <li>Terapia individual</li>
        <li>Terapia de pareja</li>
        <li>Terapia familiar</li>
        <li>Tratamiento de trastornos de ansiedad</li>
        <li>Tratamiento de depresión</li>
        <!-- Agrega más servicios o información relevante aquí -->
    </ul>
    <p>
        Nuestra misión es brindar un entorno seguro y de apoyo para todos nuestros pacientes, y trabajamos en colaboración con ellos para abordar sus necesidades específicas y metas de tratamiento.
    </p>
</div>
{% endblock %}

projeto_clinica-main/templates/terminosprivacidad.html
{% extends 'base.html' %}

{% block container %}
<div class="TerminosPrivacidad">
    <h1>{{ title }}</h1>
    <p>
        Bienvenido a nuestra página de Términos y Privacidad. Aquí encontrarás información importante sobre cómo manejamos tus datos y otros aspectos relacionados con la privacidad y el uso de nuestro sitio web.
    </p>
    <h2>Términos de Uso</h2>
    <p>
        Por favor, lee atentamente nuestros términos de uso antes de utilizar nuestros servicios. Al utilizar nuestro sitio, estás aceptando estos términos y condiciones.
    </p>
    <h2>Política de Privacidad</h2>
    <p>
        Respetamos tu privacidad y protegemos tus datos personales. Nuestra política de privacidad describe cómo recopilamos, utilizamos y protegemos tu información.
    </p>
    <h2>Cookies</h2>
    <p>
        Utilizamos cookies en nuestro sitio web para mejorar la experiencia del usuario. Puedes leer más sobre cómo utilizamos las cookies en nuestra política de cookies.
    </p>
</div>
{% endblock %}